services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio_dev_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  sidekiq:
    build: .
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
      - web
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
